
const usernames = [

'user0',
'user1',
'user2',
'user3',
'user4',
'user5',
'user6',
'user7',
'user8',
'user9',
'user10',
'user11',
'user12',
'user13',
'user14',
'user15',
'user16',
'user17',
'user18',
'user19',
'user20',
'user21',
'user22',
'user23',
'user24',
'user25',
'user26',
'user27',
'user28',
'user29',
'user30',
'user31',
'user32',
'user33',
'user34',
'user35',
'user36',
'user37',
'user38',
'user39',

];

const emails = [

    'user0@email.com',
    'user1@email.com',
    'user2@email.com',
    'user3@email.com',
    'user4@email.com',
    'user5@email.com',
    'user6@email.com',
    'user7@email.com',
    'user8@email.com',
    'user9@email.com',
    'user10@email.com',
    'user11@email.com',
    'user12@email.com',
    'user13@email.com',
    'user14@email.com',
    'user15@email.com',
    'user16@email.com',
    'user17@email.com',
    'user18@email.com',
    'user19@email.com',
    'user20@email.com',
    'user21@email.com',
    'user22@email.com',
    'user23@email.com',
    'user24@email.com',
    'user25@email.com',
    'user26@email.com',
    'user27@email.com',
    'user28@email.com',
    'user29@email.com',
    'user30@email.com',
    'user31@email.com',
    'user32@email.com',
    'user33@email.com',
    'user34@email.com',
    'user35@email.com',
    'user36@email.com',
    'user37@email.com',
    'user38@email.com',
    'user39@email.com',

];

const reactionData = [
    'this is user 0 reaction',
    'this is user 1 reaction',
    'this is user 2 reaction',
    'this is user 3 reaction',
    'this is user 4 reaction',
    'this is user 5 reaction',
    'this is user 6 reaction',
    'this is user 7 reaction',
    'this is user 8 reaction',
    'this is user 9 reaction',
    'this is user 10 reaction',
    'this is user 11 reaction',
    'this is user 12 reaction',
    'this is user 13 reaction',
    'this is user 14 reaction',
    'this is user 15 reaction',
    'this is user 16 reaction',
    'this is user 17 reaction',
    'this is user 18 reaction',
    'this is user 19 reaction',
    'this is user 20 reaction',
    'this is user 21 reaction',
    'this is user 22 reaction',
    'this is user 23 reaction',
    'this is user 24 reaction',
    'this is user 25 reaction',
    'this is user 26 reaction',
    'this is user 27 reaction',
    'this is user 28 reaction',
    'this is user 29 reaction',
    'this is user 30 reaction',
    'this is user 31 reaction',
    'this is user 32 reaction',
    'this is user 33 reaction',
    'this is user 34 reaction',
    'this is user 35 reaction',
    'this is user 36 reaction',
    'this is user 37 reaction',
    'this is user 38 reaction',
    'this is user 39 reaction',
];

const thoughtData = [
    'user 0 thought',
    'user 1 thought',
    'user 2 thought',
    'user 3 thought',
    'user 4 thought',
    'user 5 thought',
    'user 6 thought',
    'user 7 thought',
    'user 8 thought',
    'user 9 thought',
    'user 10 thought',
    'user 11 thought',
    'user 12 thought',
    'user 13 thought',
    'user 14 thought',
    'user 15 thought',
    'user 16 thought',
    'user 17 thought',
    'user 18 thought',
    'user 19 thought',
    'user 20 thought',
    'user 21 thought',
    'user 22 thought',
    'user 23 thought',
    'user 24 thought',
    'user 25 thought',
    'user 26 thought',
    'user 27 thought',
    'user 28 thought',
    'user 29 thought',
    'user 30 thought',
    'user 31 thought',
    'user 32 thought',
    'user 33 thought',
    'user 34 thought',
    'user 35 thought',
    'user 36 thought',
    'user 37 thought',
    'user 38 thought',
    'user 39 thought',
    
];

module.exports = {usernames, emails, reactionData, thoughtData};